DROP TABLE IF EXISTS ADRESSE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS CONCESSIONAIRE;
DROP TABLE IF EXISTS MARQUE;
DROP TABLE IF EXISTS VOITURE;

CREATE TABLE VOITURE(
    voiture_id VARCHAR PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR (250) NOT NULL,
    FOREIGN KEY(marque) REFERENCES marque(marque_id),
    FOREIGN KEY(client) REFERENCES client(client_id) );

CREATE TABLE MARQUE(
    marque_id VARCHAR PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR (250) NOT NULL,
    FOREIGN KEY(voiture) REFERENCES voiture(voiture_id),
    FOREIGN KEY(concessionaire) REFERENCES concessionaire(concessionaire_id) );

CREATE TABLE CONCESSIONAIRE(
    concessionaire_id VARCHAR PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR (250) NOT NULL,
    FOREIGN KEY(adresse) REFERENCES adresse(adresse_id),
    FOREIGN KEY(marque) REFERENCES adresse(marque_id) );

CREATE TABLE ADRESSE(
    adresse_id VARCHAR PRIMARY KEY NOT NULL AUTO_INCREMENT,
    adresse VARCHAR (250) NOT NULL,
    FOREIGN KEY(concessionaire) REFERENCES concessionaire(concessionaire_id) );

CREATE TABLE CLIENT(
    client_id VARCHAR PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR (250) NOT NULL,
    FOREIGN KEY(voiture) REFERENCES voiture(voiture_id) );



